server:
  port: 8081

spring:
  application:
    name: business-logic
  datasource:
    url: jdbc:postgresql://localhost:5432/solequat
    username: postgres
    password: this1pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

