server:
  port: 0

spring:
  application:
    name: worker

  data:
    mongodb:
      uri: mongodb+srv://program_creator:posgrest1132@cluster0.isxtblr.mongodb.net/LinearSystem?retryWrites=true&w=majority
      database: LinearSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/solequat
    username: postgres
    password: this1pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka