server:
  port: 0

spring:
  application:
    name: worker

  datasource:
    url: jdbc:postgresql://localhost:5432/solequat_worker
    username: postgres
    password: this1pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka