server:
  port: 8765

spring:
  application:
    name: gateway

zuul:
  routes:
    worker:
      path: /worker/**
      serviceId: worker
      sensitive-headers:
        -
      strip-prefix: true
    business-logic:
      path: /business-logic/**
      serviceId: business-logic
      sensitive-headers:
        -
      strip-prefix: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

