server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: registration
          uri: lb://business-logic
          predicates:
            - Path=/api/v1/registration
            - Method=POST
        - id: confirm
          uri: lb://business-logic
          predicates:
            - Path=/api/v1/registration/confirm
            - Method=GET
        - id: authenticate
          uri: lb://business-logic
          predicates:
            - Path=/api/v1/registration/authenticate
            - Method=GET


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


